### ISSUE TITLE
Support for Windows VMs

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [meffie/molecule-proxmox#10]
Hi,

Our workflows include a mix of Windows and Linux guests. As such, I would like to throw into the mix a request for Windows VM support.

Thank you for this great driver!

**Comment by meffie** [comment]
> Hi,
> 
> Our workflows include a mix of Windows and Linux guests. As such, I would like to throw into the mix a request for Windows VM support.
> 
> Thank you for this great driver!

Thank you.  I currently am windows free, but it would be a nice addition.  I'm not sure what would
need to be done. I would imagine most of the work would be to setup the windows template, and the driver would just clone it.

Currently, issue 3 is a more pressing issue.  We need to figure out how to work with current versions of Molecule, which changed how the schema validation works.

**Comment by tmccomb** [comment]
I'm able to use this with Windows servers no issue. Specifically, I'm using the libvirt version of the jborean93 Windows 2019 vagrant box. (Had to import it into proxmox, and set up a template to use it. ) 

In molecule, I set the hosts' winrm connections, and it magically seems to work. 

`ansible_become: false
ansible_user: vagrant
ansible_password: vagrant
ansible_port: 5986

ansible_connection: psrp
ansible_psrp_cert_validation: ignore
ansible_psrp_operation_timeout: 120
ansible_psrp_read_timeout: 120
ansible_winrm_transport: ntlm
ansible_winrm_read_timeout_sec: 140
ansible_winrm_operation_timeout_sec: 120
ansible_winrm_server_cert_validation: ignore
`

There were a couple tweaks I made to the molecule create.yml file as well, but I'm not sure they had any effect. (I think I added the "full" option, as well as the "ostype" - both added as part of the proxmox_kvm task)

And I needed to add a few tasks to my prepare.yml - wait_for_connection at the beginning, and I think I need to add something to set the Windows hostnames to the same as the VM name. (haven't done that yet) (it was getting late in the evening, I don't recall everything)

YMMV

**Comment by meffie** [comment]
> There were a couple tweaks I made to the molecule create.yml file as well, but I'm not sure they had any effect. (I think I added the "full" option, as well as the "ostype" - both added as part of the proxmox_kvm task)

> And I needed to add a few tasks to my prepare.yml - wait_for_connection at the beginning, and I think I need to add something to set the Windows hostnames to the same as the VM name. (haven't done that yet) (it was getting late in the evening, I don't recall everything)

Thanks for the info @tmccomb .  Let me know if you really need those changes, and if so, can you share a patch?
