### ISSUE TITLE
Add authentication realm to documentation

### ISSUE THREAD

**Issue by IamLunchbox** [meffie/molecule-proxmox#14]
When using an API-Token, Proxmox was complaining about not being able to authenticate. My user was created in the pve-realm, other realms might be provided by pam or ldap.

I had to fix this by adding the realm to the authentication information. I don't know if this workaround is only needed for the api-token authentication, but as far as I know, the proxmox-api always expects a login with the given realm, e.g. [here](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/access/password). Maybe proxmoxer implies pam by default, but at least I had to adjust the authentication user like this:

```yml
driver:
  name: molecule-proxmox
  options:
    api_user: bot@pve #here
    [...]
```

I would propose to enhance to the documentation in this regard and created it myself -  but since you were already working on the readme and I had not yet time to verify the behavior with password-based logins, I opted for an issue instead if an PR.

**Comment by meffie** [comment]
Thanks. The api_user has been a point of confusion. I believe the format is always "name@realm".

**Comment by meffie** [comment]
Is this better?

19aeb11 README: Add realm to api_user examples

**Comment by meffie** [comment]
Apologies, I needed to rebase the main branch due to an earlier mistake. The new commit is

  99221bf README: Add realm to api_user examples

**Comment by IamLunchbox** [comment]
Thank you for your work! I think that's enough - otherwise I'll create a PR ;)
