### ISSUE TITLE
Variables for hardware and cloudinit

### ISSUE THREAD

**Issue by wontfixthis** [meffie/molecule-proxmox#7]
First of all - thanks a lot for this driver!! It helped me a lot running my tests somewhere else than on my Apple M1.

It would be awesome to set variables for cloudinit and other PVE configurations in the options section of the driver.
At the moment we have to copy the vm template from an fully set up virtual machine (i.e. network interface is set and ssh keys are defined for cloudinit etc.).

Maybe there is already something to solve this issue -> then sorry for the question.

**Comment by meffie** [comment]
Excellent. Thanks. 

Yes, cloudinit variables probably would be very useful indeed.


________________________________________
From: wontfixthis ***@***.***>
Sent: Monday, January 9, 2023 9:38 AM
To: meffie/molecule-proxmox
Cc: Subscribed
Subject: [meffie/molecule-proxmox] Variables for hardware and cloudinit (Issue #7)

First of all - thanks a lot for this driver!! It helped me a lot running my tests somewhere else than on my Apple M1.

It would be awesome to set variables for cloudinit and other PVE configurations in the options section of the driver.
At the moment we have to copy the vm template from an fully set up virtual machine (i.e. network interface is set and ssh keys are defined for cloudinit etc.).

Maybe there is already something to solve this issue -> then sorry for the question.
